name: CI-CD Pipeline

on:
  pull_request:

  push:
    branches:
      - main

jobs:

  sonar:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: SonarQube Scan
        run: echo "Running SonarQube Scan"

  docker:

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    environment:
      name: production

    steps:

      - uses: actions/checkout@v4

      - uses: ./.github/actions/docker-build
        with:
          image_name: hello-app
          image_tag: latest
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
